cc_binary(
    name="parser",
    srcs=["parser.cpp","parser.hpp"],
#    hdrs=["parser.hpp"],
    deps=[
        "//third_party/glm",
        "//third_party/freetype:freetype"
    ],
    visibility=["//visibility:public"]
)
